name: KPlugin
version: 1.1
author: kenYUNOT
main: com.kftang.KPlugin.KPlugin
website: kftang.com
commands:
  kplugin:
    description: Display information about KPlugin
    usage: /kplugin
  rtp:
    description: Teleport to a random location
    usage: /rtp
  vote:
    description: Vote for different actions
    usage: /vote <weather/time> <setting>
